# ####################################### #
# 此文件是本項目的主配置文件，所有配置將被應用 #
# ####################################### #

# 服務器的配置
server:
  # Servlet（Java用於處理請求的組件）的配置
  servlet:
    # 編碼配置
    encoding:
      # 强制使用指定的編碼
      force: true
      # 字元集
      charset: UTF-8

# Spring的配置
spring:
  # Profile的配置
  profiles:
    # 激活哪些Profile配置
    active: dev
  # Jackson框架的配置
  jackson:
    # 響應的JSON結果中默認包含什麼樣的屬性
    default-property-inclusion: non_null
  # 資料源的配置
  datasource:
    # 連接資料庫的URL
    url: jdbc:mysql://${meimall.datasource.host}:${meimall.datasource.port}/meimei_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 資料庫用户名
    username: ${meimall.datasource.username}
    # 資料庫密碼
    password: ${meimall.datasource.password}
    # Druid連接池的配置
    druid:
      # 初始化連接數量
      initial-size: ${meimall.datasource.initial-size}
      # 最大激活數量
      max-active: ${meimall.datasource.max-active}
  # Redis配置
  redis:
    # 主機
    host: ${meimall.redis.host}
    # 通訊埠
    port: ${meimall.redis.port}
    # 用户名
    username: ${miemall.redis.username}
    # 密碼
    password: ${meimall.redis.password}

# MyBatis Plus配置
mybatis-plus:
  # 配置SQL語句的XML文件的位置
  mapper-locations: classpath:mappers/**/*.xml

# Knife4j配置
knife4j:
  # 開啟增强模式
  enable: true
