# ####################################### #
# 此文件是本項目的主配置文件，所有配置將被應用 #
# ####################################### #

# 服務器的配置
server:
  # Servlet（Java用於處理請求的組件）的配置
  servlet:
    # 編碼配置
    encoding:
      # 强制使用指定的編碼
      force: true
      # 字元集
      charset: UTF-8

# Spring的配置
spring:
  # Profile的配置
  profiles:
    # 激活哪些Profile配置
    active: dev
  # Jackson框架的配置
  jackson:
    # 響應的JSON結果中默認包含什麼樣的屬性
    default-property-inclusion: non_null

# Knife4j配置
knife4j:
  # 開啟增強模式
  enable: true
